# Supported funding platforms for Vibra Music
# See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [Fortunehack45]
# buy_me_a_coffee: your_username
# ko_fi: your_username
# patreon: your_username
custom: ['https://fortuneadebayo.space/']
